
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.63
distribution_type: module
version: 2.00_04
name: JSAN-Shell
author: Adam Kennedy <F<adam@ali.as>>, L<http://ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  Getopt::Long: 2.34
  perl: 5.6.0
  Term::ReadLine: 1.01
  JSAN::Client: 0.13
abstract: JavaScript Archive Network Client Shell
