name: JSAN-Shell
version: 2.00_02
abstract: The JavaScript Archive Network (JSAN) Shell 2
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  Term::ReadLine: 1.01
  Getopt::Long: 2.34
  JSAN::Client: 0.08
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
