abstract: JavaScript Archive Network Client Shell
author: Adam Kennedy <F<adam@ali.as>>, L<http://ali.as>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: JSAN-Shell
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::HomeDir: 0.63
  File::ShareDir: 0.05
  Getopt::Long: 2.34
  JSAN::Client: 0.16
  LWP::Online: 0.02
  Mirror::YAML: 0.02
  Term::ReadLine: 1.01
  Term::ReadLine::Perl: 1.0302
  perl: 5.005
version: 2.00_05
